// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type AppointmentClient struct {
	ID          string
	Name        string
	PhoneNumber string
	Email       string
	CreatedAt   sql.NullTime
}
