// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package db

import (
	"context"
)

const getClient = `-- name: GetClient :one
SELECT id, name, phone_number, email, created_at FROM appointment_clients
WHERE id = ? LIMIT 1
`

func (q *Queries) GetClient(ctx context.Context, id string) (AppointmentClient, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i AppointmentClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
