#!/bin/bash -e

all:
    TELEGRAM_TOKEN=$(cat ~/Sync/veterinary-clinic/telegram-token) \
        NOTION_TOKEN=$(cat ~/Sync/veterinary-clinic/notion-token) \
        NOTION_SERVICES_DATABASE_ID=$(cat ~/Sync/veterinary-clinic/notion-services-db-id) \
        NOTION_RECORDS_DATABASE_ID=$(cat ~/Sync/veterinary-clinic/notion-records-db-id) \
        go run cmd/app/*.go --config config/config.yml

build:
    CGO_ENABLED=1 go build -o bin/app cmd/app/*.go

run:
    TELEGRAM_TOKEN=$(cat ~/Sync/veterinary-clinic/telegram-token) \
        NOTION_TOKEN=$(cat ~/Sync/veterinary-clinic/notion-token) \
        NOTION_SERVICES_DATABASE_ID=$(cat ~/Sync/veterinary-clinic/notion-services-db-id) \
        NOTION_RECORDS_DATABASE_ID=$(cat ~/Sync/veterinary-clinic/notion-records-db-id) \
        ./bin/app --config config/config.yml

test:
    go test ./...

lint:
    golangci-lint run ./...
