#!/bin/bash -e

env: all run prof migrate debug-env query
    if [ -f .env.local ]
    then
        export $(cat .env.local | xargs)
    fi
    if [ -d ~/Sync/veterinary-clinic ]
    then
        export TELEGRAM_TOKEN=$(cat ~/Sync/veterinary-clinic/telegram-token)
        export NOTION_TOKEN=$(cat ~/Sync/veterinary-clinic/notion-token)
        export APPOINTMENT_NOTION_SERVICES_DATABASE_ID=$(cat ~/Sync/veterinary-clinic/notion-services-db-id)
        export APPOINTMENT_NOTION_RECORDS_DATABASE_ID=$(cat ~/Sync/veterinary-clinic/notion-records-db-id)
        export APPOINTMENT_NOTION_BREAKS_DATABASE_ID=$(cat ~/Sync/veterinary-clinic/notion-breaks-db-id)
        export APPOINTMENT_NOTION_CUSTOMERS_DATABASE_ID=$(cat ~/Sync/veterinary-clinic/notion-customers-db-id)
        export APPOINTMENT_NOTIFICATIONS_ADMIN_IDENTITY=$(cat ~/Sync/veterinary-clinic/notifications-admin-id)
        export PROFILER_REMOTE_ADDRESS=$(cat ~/Sync/veterinary-clinic/prof-address)
    fi
    export STORAGE_PATH=storage/storage.db
    export STORAGE_MIGRATIONS_PATH=db/migrations

all:
    air -- --config config/config.yml

query:
    curl -X POST "https://api.notion.com/v1/databases/${APPOINTMENT_NOTION_CUSTOMERS_DATABASE_ID}/query" \
    -H 'Authorization: Bearer '"$NOTION_TOKEN"'' \
    -H 'Notion-Version: 2022-06-28' \
    -H "Content-Type: application/json" \
    --data '{
    "filter": {
        "or": [
            {
                "property": "Записи",
                "relation": {
                    "contains": "eb857aa769f448efb6e1ad4e52c12051"
                }
            }
        ]
    }
    }'

build:
    CGO_ENABLED=1 go build -tags migrate -o bin/app cmd/app/main.go

run:
    ./bin/app --config config/config.yml

debug-env:
    env > .env.debug.local

prof:
    go tool pprof -http :8081 "${PROFILER_REMOTE_ADDRESS}/debug/pprof/$1"

test:
    go test ./...

lint:
    golangci-lint run ./...

## DATABASE

db:
    sqlc generate

# Database queries lint
qlint:
    sqlc vet

# Migration create
mc:
    migrate create -ext sql -dir $STORAGE_MIGRATIONS_PATH -seq $1

migrate:
    CGO_ENABLED=1 go run -tags migrate cmd/migrate/main.go
