storage:
  path: "./storage/storage.db"
logger:
  level: debug
  handler_type: pretty
profiler:
  enabled: true
  address: 0.0.0.0:6060
metrics:
  enabled: true
  address: 0.0.0.0:9099
telegram:
  web_handler_address: 0.0.0.0:6012
  # This is should be a https url (without end slash) to the web handler address
  # web_handler_url: 
  calendar_web_app_url: https://x0k.github.io/telegram-web-inputs/calendar
production_calendar:
  url: https://gist.githubusercontent.com/x0k/e45728deb54612d6043b8aa7ec4d1cef/raw/55b6006d74fa4e50568bb601b36a7248f9613e1b/calendar.json
