storage:
  path: "./storage/storage.db"
logger:
  level: debug
  handler_type: pretty
profiler:
  enabled: true
  address: 0.0.0.0:6060
metrics:
  enabled: true
  address: 0.0.0.0:9099
telegram:
  web_handler_address: 0.0.0.0:6012
  web_handler_url: http://127.0.0.1:6012
  calendar_web_app_url: https://x0k.github.io/telegram-web-inputs/calendar
